### ISSUE TITLE
Games?

### ISSUE THREAD

**Issue by burdges** [w3f/Grants-Program#503]
We expect parachains/parathreads can deliver respectable performance for dedicated applications, we need some demonstration applications that require more parachain blockspace than these little distributed finance things.  It's clear games provide an obvious direction, but which games played sound fun with a distributed database? 

We need randomness for games which requires that game developers learn to use verifiable random functions (VRFs).  I've given [one talk around fun VRF usages](https://www.youtube.com/watch?v=VyiG_JNxvIw) and envision giving more.

Could world building games achieve much?  I suppose many need too much storage, but if the world expires after 24 hours then they could operate by UTXO using previous blocks as world segments.  Is it reasonable to only permit world segments to update infrequently so that each update occupies a whole block, maybe via some off chain state channel?  If so, there exist [open source minecraft games](https://opensource.com/alternatives/minecraft) one could fork, but one should explore and simplify the [game rules](https://minecraft.fandom.com/wiki/Game_rule). 

I suppose [Illuminati](https://en.wikipedia.org/wiki/Illuminati_(game)) clone or other collectable card games sound like both easy VRF based randomness, minimal on-chain data but still far too much for our compeditors, and world building, but Illuminati itself runs into copyright issues.  Could on-chain governance make the cards?  

I've been quite impressed by [Cheapass Games](https://cheapass.com/free-games/) so maybe their card games could provide a source of inspiration.

**Comment by darkfriend77** [comment]
I agree that card games and other turn-based games might not be a technical novel achievement, but providing a solid solution for state channels for up to N=10 players in substrate would allow to get a lot of game concepts up and running in the substrate ecosystem.

It's one thing to make a blockchain game and another to have it compete on the market with non-blockchain games.

For DOTMog, we need state channels for the duels, which will be turn-based for now^^. So we will work on such a solution. Already with state channels, I see a lot of challenges even for a turn-based game.

Maybe a good start would be to start a group to work out some solutions that solve basic requirements concerning state channels, otherwise, a lot of the games will just drop back to the centralized off-chain game server, allowing them to use both worlds power, which is very tempting.

- Hidding player Informations (hidden cards), but still preventing malicious gameplay.
- Handling rage quitting players
- Handling randomness
- Light client vs. full client

Maybe having state channels add up an arbitrary party could solve some of the challenges. Not sure but in a state channel with only a few players, a team-up on malicious game nodes might open an attack vector.

**Comment by EdwardAThomson** [comment]
Yeah, I *think* Xaya's solution should do some of what you are looking for although I'm not at the correct dev level to verify that. I dare say that their Xaya won't perfectly cover everything you want to do, so some R&D still needed. I'm sure you could have a conversation with the team, happy to do an intro although they are generally freely chatting over in the DGA. While that group is not Substrate-only, it is focused on fully decentralized games. One option is to create a working group there, since this is really a very general problem for decentralized games and some teams have worked on solutions already,

**Comment by Noc2** [comment]
@darkfriend: Fyi: We recently followed-up with Celer. They promised to continue to work on [cChannel](https://github.com/celer-network/cChannel-substrate) and [cApps-substrate](https://github.com/celer-network/cApps-substrate) later this year. Apart from this https://perun.network/ is close to finishing their first grant: https://github.com/w3f/Grant-Milestone-Delivery/pull/235 + https://github.com/w3f/Grant-Milestone-Delivery/pull/236 and so far it looks quite promising.  So we are probably going to continue to work with them.

**Comment by stechu** [comment]
How about DarkForest?

**Comment by web3cryptowallet** [comment]
Hi, I develop dApps gamedev platform https://twitter.com/Web3Wallet

**Comment by Noc2** [comment]
I’m closing the issue, since by now we have quite a few teams focused on games that are close on launching their parachains.
