### ISSUE TITLE
Updating Support Email to URL

### ISSUE THREAD

**Issue by imadarai** [w3f/Grants-Program#738]
I'm working in collaboration with @michalisFr to update support email (`support@polkadot.network`) to url (`https://support.polkadot.network`).  

We noticed the only mention is on [Zondax-Support](https://github.com/w3f/Grants-Program/blob/9ff879a5f358220e20aae1dcaf39302df2769eb6/applications/Zondax-Support.md) page, and based on the context it seems fit to have one of the educators update the content. 

Our goal is to completely get rid of public mention of support@polkadot.network on all the web-properties and have all the traffic funnel through the website - `support.polkadot.network`.  

cc: @michalisFr

**Comment by semuelle** [comment]
Hi @imadarai, thanks for raising this. The document you are referring to is a grant application, though. I'm not sure it should be modified retrospectively. The documents in that folder aren't usually read by anyone other than potential grantees. 

If you really want it gone, I could replace the address with a placeholder string like `support at polkadot` or `polkadot email support`?

**Comment by michalisFr** [comment]
@semuelle This is indeed the odd occurrence and leaving it as is isn't the end of the world for sure. However, since this is Zondax's proposal it might turn up in some search for the Ledger app, so it'd be good to direct users somewhere.

Personally I think changing it doesn't alter the context at all, since `support.polkadot.network` is the new central support "hub" Zondax is referring to. But if you want to only change it to a placeholder, does `polkadot support` work? Or even leaving it as is, is no big deal. This occurrence is minor really.

**Comment by semuelle** [comment]
If both addresses refer to the same entity, we might as well replace it. I'll  check with Legal.

**Comment by Noc2** [comment]
I updated it, see https://github.com/w3f/Grants-Program/commit/22428da766fd38b068733d842be84801ea931703

**Comment by imadarai** [comment]
Thanks @semuelle & @Noc2 !!
